// <auto-generated />
using System;
using ArtGestion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtGestion.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416132248_AddAuthenticationSetup")]
    partial class AddAuthenticationSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtGestion.Models.Alerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean");

                    b.Property<bool>("Lue")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("TitreExploitationId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeAlerte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UtilisateurResponsableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UtilisateurResponsableId");

                    b.HasIndex("TitreExploitationId", "TypeAlerte")
                        .IsUnique();

                    b.ToTable("Alertes");
                });

            modelBuilder.Entity("ArtGestion.Models.Exploitant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeExploitant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateSaisie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomExploitant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeEntrepriseId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.Property<int>("VilleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodeExploitant");

                    b.HasIndex("RegionId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TypeEntrepriseId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("VilleId");

                    b.ToTable("Exploitants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeExploitant = "EXP001",
                            DateSaisie = new DateTime(2026, 4, 16, 13, 22, 48, 238, DateTimeKind.Utc).AddTicks(3373),
                            NomExploitant = "MTN Cameroun",
                            RegionId = 1,
                            ServiceId = 1,
                            TypeEntrepriseId = 1,
                            UtilisateurId = 1,
                            VilleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CodeExploitant = "EXP002",
                            DateSaisie = new DateTime(2026, 4, 16, 13, 22, 48, 238, DateTimeKind.Utc).AddTicks(3381),
                            NomExploitant = "Orange Cameroun",
                            RegionId = 1,
                            ServiceId = 1,
                            TypeEntrepriseId = 1,
                            UtilisateurId = 1,
                            VilleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CodeExploitant = "EXP003",
                            DateSaisie = new DateTime(2026, 4, 16, 13, 22, 48, 238, DateTimeKind.Utc).AddTicks(3383),
                            NomExploitant = "Nexttel",
                            RegionId = 2,
                            ServiceId = 1,
                            TypeEntrepriseId = 2,
                            UtilisateurId = 1,
                            VilleId = 2
                        });
                });

            modelBuilder.Entity("ArtGestion.Models.LogAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("EntiteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeAction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("LogsActions");
                });

            modelBuilder.Entity("ArtGestion.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Code = "LT",
                            Nom = "Littoral"
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Code = "SW",
                            Nom = "Sud-Ouest"
                        });
                });

            modelBuilder.Entity("ArtGestion.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Code = "SSVTSE",
                            Nom = "Service du Suivi des Services, de la Veille Technologique et des Statistiques Économiques"
                        });
                });

            modelBuilder.Entity("ArtGestion.Models.TitreExploitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateSaisie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateSignature")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExploitantId")
                        .HasColumnType("integer");

                    b.Property<string>("FrequencesAssignees")
                        .HasColumnType("text");

                    b.Property<int?>("NombreTitres")
                        .HasColumnType("integer");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceTitre")
                        .HasColumnType("text");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TypeReseauId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeTitreId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExploitantId");

                    b.HasIndex("ReferenceTitre");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TypeReseauId");

                    b.HasIndex("TypeTitreId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("TitresExploitation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            DateExpiration = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateSaisie = new DateTime(2026, 4, 16, 13, 22, 48, 238, DateTimeKind.Utc).AddTicks(3411),
                            DateSignature = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExploitantId = 1,
                            NombreTitres = 1,
                            ReferenceTitre = "TITRE-001",
                            ServiceId = 1,
                            Statut = "Actif",
                            TypeTitreId = 1,
                            UtilisateurId = 1
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            DateExpiration = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateSaisie = new DateTime(2026, 4, 16, 13, 22, 48, 238, DateTimeKind.Utc).AddTicks(3423),
                            DateSignature = new DateTime(2021, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExploitantId = 2,
                            NombreTitres = 2,
                            ReferenceTitre = "TITRE-002",
                            ServiceId = 1,
                            Statut = "Bientôt expiré",
                            TypeTitreId = 1,
                            UtilisateurId = 1
                        },
                        new
                        {
                            Id = 3,
                            Actif = false,
                            DateExpiration = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateSaisie = new DateTime(2026, 4, 16, 13, 22, 48, 238, DateTimeKind.Utc).AddTicks(3425),
                            DateSignature = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExploitantId = 3,
                            NombreTitres = 1,
                            ReferenceTitre = "TITRE-003",
                            ServiceId = 1,
                            Statut = "Expiré",
                            TypeTitreId = 1,
                            UtilisateurId = 1
                        });
                });

            modelBuilder.Entity("ArtGestion.Models.TypeEntreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypesEntreprise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Libelle = "Opérateur"
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Libelle = "Fournisseur"
                        });
                });

            modelBuilder.Entity("ArtGestion.Models.TypeReseau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypesReseau");
                });

            modelBuilder.Entity("ArtGestion.Models.TypeTitre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<int>("DureeValidite")
                        .HasColumnType("integer");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniteDuree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TypesTitre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            DureeValidite = 5,
                            Libelle = "Licence",
                            UniteDuree = "Ans"
                        });
                });

            modelBuilder.Entity("ArtGestion.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EstResponsableService")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            DateCreation = new DateTime(2026, 4, 16, 13, 22, 48, 238, DateTimeKind.Utc).AddTicks(3300),
                            Email = "admin@art.local",
                            EstResponsableService = true,
                            Login = "admin",
                            MotDePasseHash = "temp-hash",
                            NomComplet = "Admin SSVTSE",
                            Role = "Admin",
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("ArtGestion.Models.Ville", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Villes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Nom = "Douala",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Nom = "Buea",
                            RegionId = 2
                        });
                });

            modelBuilder.Entity("ArtGestion.Models.Alerte", b =>
                {
                    b.HasOne("ArtGestion.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArtGestion.Models.TitreExploitation", "TitreExploitation")
                        .WithMany()
                        .HasForeignKey("TitreExploitationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtGestion.Models.Utilisateur", "UtilisateurResponsable")
                        .WithMany()
                        .HasForeignKey("UtilisateurResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Service");

                    b.Navigation("TitreExploitation");

                    b.Navigation("UtilisateurResponsable");
                });

            modelBuilder.Entity("ArtGestion.Models.Exploitant", b =>
                {
                    b.HasOne("ArtGestion.Models.Region", "Region")
                        .WithMany("Exploitants")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtGestion.Models.Service", "Service")
                        .WithMany("Exploitants")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtGestion.Models.TypeEntreprise", "TypeEntreprise")
                        .WithMany("Exploitants")
                        .HasForeignKey("TypeEntrepriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtGestion.Models.Utilisateur", "Utilisateur")
                        .WithMany("ExploitantsCrees")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtGestion.Models.Ville", "Ville")
                        .WithMany("Exploitants")
                        .HasForeignKey("VilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Service");

                    b.Navigation("TypeEntreprise");

                    b.Navigation("Utilisateur");

                    b.Navigation("Ville");
                });

            modelBuilder.Entity("ArtGestion.Models.LogAction", b =>
                {
                    b.HasOne("ArtGestion.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArtGestion.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Service");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ArtGestion.Models.TitreExploitation", b =>
                {
                    b.HasOne("ArtGestion.Models.Exploitant", "Exploitant")
                        .WithMany("TitresExploitation")
                        .HasForeignKey("ExploitantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtGestion.Models.Service", "Service")
                        .WithMany("TitresExploitation")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtGestion.Models.TypeReseau", "TypeReseau")
                        .WithMany("TitresExploitation")
                        .HasForeignKey("TypeReseauId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArtGestion.Models.TypeTitre", "TypeTitre")
                        .WithMany("TitresExploitation")
                        .HasForeignKey("TypeTitreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtGestion.Models.Utilisateur", "Utilisateur")
                        .WithMany("TitresCrees")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exploitant");

                    b.Navigation("Service");

                    b.Navigation("TypeReseau");

                    b.Navigation("TypeTitre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("ArtGestion.Models.Utilisateur", b =>
                {
                    b.HasOne("ArtGestion.Models.Service", "Service")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ArtGestion.Models.Ville", b =>
                {
                    b.HasOne("ArtGestion.Models.Region", "Region")
                        .WithMany("Villes")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ArtGestion.Models.Exploitant", b =>
                {
                    b.Navigation("TitresExploitation");
                });

            modelBuilder.Entity("ArtGestion.Models.Region", b =>
                {
                    b.Navigation("Exploitants");

                    b.Navigation("Villes");
                });

            modelBuilder.Entity("ArtGestion.Models.Service", b =>
                {
                    b.Navigation("Exploitants");

                    b.Navigation("TitresExploitation");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("ArtGestion.Models.TypeEntreprise", b =>
                {
                    b.Navigation("Exploitants");
                });

            modelBuilder.Entity("ArtGestion.Models.TypeReseau", b =>
                {
                    b.Navigation("TitresExploitation");
                });

            modelBuilder.Entity("ArtGestion.Models.TypeTitre", b =>
                {
                    b.Navigation("TitresExploitation");
                });

            modelBuilder.Entity("ArtGestion.Models.Utilisateur", b =>
                {
                    b.Navigation("ExploitantsCrees");

                    b.Navigation("TitresCrees");
                });

            modelBuilder.Entity("ArtGestion.Models.Ville", b =>
                {
                    b.Navigation("Exploitants");
                });
#pragma warning restore 612, 618
        }
    }
}
